version: '3.9'
services:
  fetcher:
    build: .
    command: python3 main.py --schedule
    restart: always
    volumes:
      - 'fetcher-data:/work/data'

  web:
    image: nginx:1.21
    restart: always
    ports:
      - '${NGINX_PORT:-127.0.0.1:8000}:80'
    volumes:
      - './default.nginx:/etc/nginx/conf.d/default.conf'
      - 'fetcher-data:/var/www/html/data'

volumes:
  fetcher-data:
